version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.31
    command:
      --default-authentication-plugin=mysql_native_password
      --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - '3306:3306'

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"